# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Users/thefa/.jdks/ms-25.0.4.1

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.5

# Mod Properties
mod_version=2.0.1
# ^^^ Format: big update, update, patch
maven_group=org.wavemelon
archives_base_name=funnitiers

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.160.0+26.2
modmenu_version=20.0.3
